language: python
python:
  - "3.7.4"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install codecov
# command to run tests
script:
- pytest
- pylint lyrics_predictor/*.py
- coverage run test_lyrics_predictor.py

# # Push the results back to codecov
after_success:
  - codecov
